s=set()
s.add('amol')
s.add('priya')
s.add('mira')
s.add('dipti')
s.add('anil')
print('After adding five names',s)
s.remove('anil')
s.add('ANIL')
print('After modifying anil',s)
s.remove('dipti')
s.remove('mira')
print('After deletinf dipti and mira',s)